name: discord-ads-bot-build
services:
  discord-ads-bot:
    build: .
    container_name: discord-ads-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_DIR: /data
    volumes:
      - ./data:/data
